/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package npinjamruang;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author dyana
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

        lIconD.setIcon(ImageHelper.getIcon("/img/home.png", 20, 20));
        lIconD1.setIcon(ImageHelper.getIcon("/img/db.png", 20, 20));

        pPinjam.setOpaque(true);
        pPinjam.putClientProperty(FlatClientProperties.STYLE, "arc: 15");

        pPinjam.putClientProperty("JComponent.arc", 15);
        pPinjam.putClientProperty("JComponent.rounding", 15);

        pPinjam.setPreferredSize(new Dimension(180, 40));
        bPinjam.setPreferredSize(new Dimension(74, 20));
        bPinjam.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_nav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_side = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menus = new javax.swing.JPanel();
        pPinjam = new javax.swing.JPanel();
        pLine = new javax.swing.JPanel();
        lIconD = new javax.swing.JLabel();
        bPinjam = new javax.swing.JLabel();
        pHistory = new javax.swing.JPanel();
        pLine1 = new javax.swing.JPanel();
        lIconD1 = new javax.swing.JLabel();
        bHistory = new javax.swing.JLabel();
        p_content = new javax.swing.JPanel();
        pMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_nav.setBackground(new java.awt.Color(0, 102, 204));
        p_nav.setPreferredSize(new java.awt.Dimension(800, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Pinjam");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("RuangSYS");

        javax.swing.GroupLayout p_navLayout = new javax.swing.GroupLayout(p_nav);
        p_nav.setLayout(p_navLayout);
        p_navLayout.setHorizontalGroup(
            p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_navLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_navLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(699, Short.MAX_VALUE))
        );
        p_navLayout.setVerticalGroup(
            p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_navLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(p_nav, java.awt.BorderLayout.PAGE_START);

        p_side.setPreferredSize(new java.awt.Dimension(200, 525));

        menus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pPinjam.setBackground(new java.awt.Color(174, 200, 164));
        pPinjam.setPreferredSize(new java.awt.Dimension(150, 30));
        pPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pPinjamMouseEntered(evt);
            }
        });

        pLine.setBackground(new java.awt.Color(174, 200, 164));
        pLine.setPreferredSize(new java.awt.Dimension(5, 28));

        javax.swing.GroupLayout pLineLayout = new javax.swing.GroupLayout(pLine);
        pLine.setLayout(pLineLayout);
        pLineLayout.setHorizontalGroup(
            pLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pLineLayout.setVerticalGroup(
            pLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        lIconD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        lIconD.setPreferredSize(new java.awt.Dimension(20, 20));

        bPinjam.setBackground(new java.awt.Color(174, 200, 164));
        bPinjam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bPinjam.setText("Pinjam Ruang");
        bPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bPinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bPinjamMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pPinjamLayout = new javax.swing.GroupLayout(pPinjam);
        pPinjam.setLayout(pPinjamLayout);
        pPinjamLayout.setHorizontalGroup(
            pPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPinjamLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lIconD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pPinjamLayout.setVerticalGroup(
            pPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPinjamLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lIconD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menus.add(pPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        pHistory.setBackground(new java.awt.Color(174, 200, 164));
        pHistory.setPreferredSize(new java.awt.Dimension(150, 30));
        pHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHistoryMouseEntered(evt);
            }
        });

        pLine1.setBackground(new java.awt.Color(174, 200, 164));
        pLine1.setPreferredSize(new java.awt.Dimension(5, 28));

        javax.swing.GroupLayout pLine1Layout = new javax.swing.GroupLayout(pLine1);
        pLine1.setLayout(pLine1Layout);
        pLine1Layout.setHorizontalGroup(
            pLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pLine1Layout.setVerticalGroup(
            pLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        lIconD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/db.png"))); // NOI18N
        lIconD1.setPreferredSize(new java.awt.Dimension(20, 20));

        bHistory.setBackground(new java.awt.Color(174, 200, 164));
        bHistory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bHistory.setText("History");
        bHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bHistoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pHistoryLayout = new javax.swing.GroupLayout(pHistory);
        pHistory.setLayout(pHistoryLayout);
        pHistoryLayout.setHorizontalGroup(
            pHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHistoryLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lIconD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pHistoryLayout.setVerticalGroup(
            pHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHistoryLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lIconD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menus.add(pHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, -1));

        jScrollPane1.setViewportView(menus);

        javax.swing.GroupLayout p_sideLayout = new javax.swing.GroupLayout(p_side);
        p_side.setLayout(p_sideLayout);
        p_sideLayout.setHorizontalGroup(
            p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_sideLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_sideLayout.setVerticalGroup(
            p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        getContentPane().add(p_side, java.awt.BorderLayout.LINE_START);

        p_content.setBackground(new java.awt.Color(255, 255, 255));

        pMain.setBackground(new java.awt.Color(255, 255, 255));
        pMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout p_contentLayout = new javax.swing.GroupLayout(p_content);
        p_content.setLayout(p_contentLayout);
        p_contentLayout.setHorizontalGroup(
            p_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_contentLayout.setVerticalGroup(
            p_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(p_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(814, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPinjamMouseClicked

        pPinjam.setBackground(new Color(231, 239, 199));
        pLine.setBackground(new Color(138, 120, 78));

        pMain.removeAll();
        pMain.add(new Ruangan(this));
        pMain.repaint();
        pMain.revalidate();
    }//GEN-LAST:event_bPinjamMouseClicked

    private void bPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPinjamMouseEntered
        // TODO add your handling code here:
        pPinjam.setBackground(new Color(231, 239, 199));
        pLine.setBackground(new Color(138, 120, 78));
    }//GEN-LAST:event_bPinjamMouseEntered

    private void bPinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPinjamMouseExited
        // TODO add your handling code here:
        pPinjam.setBackground(new Color(174, 200, 164));
        pLine.setBackground(new Color(174, 200, 164));
    }//GEN-LAST:event_bPinjamMouseExited

    private void pPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPinjamMouseClicked

    }//GEN-LAST:event_pPinjamMouseClicked

    private void pPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPinjamMouseEntered

    }//GEN-LAST:event_pPinjamMouseEntered

    private void bHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHistoryMouseClicked
        pHistory.setBackground(new Color(231, 239, 199));
        pLine1.setBackground(new Color(138, 120, 78));

        pMain.removeAll();
        pMain.add(new History(this));
        pMain.repaint();
        pMain.revalidate();

    }//GEN-LAST:event_bHistoryMouseClicked

    private void bHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHistoryMouseEntered
        pHistory.setBackground(new Color(231, 239, 199));
        pLine1.setBackground(new Color(138, 120, 78));
    }//GEN-LAST:event_bHistoryMouseEntered

    private void bHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHistoryMouseExited
        pHistory.setBackground(new Color(174, 200, 164));
        pLine1.setBackground(new Color(174, 200, 164));
    }//GEN-LAST:event_bHistoryMouseExited

    private void pHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHistoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pHistoryMouseClicked

    private void pHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHistoryMouseEntered

    }//GEN-LAST:event_pHistoryMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bHistory;
    private javax.swing.JLabel bPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lIconD;
    private javax.swing.JLabel lIconD1;
    private javax.swing.JPanel menus;
    public javax.swing.JPanel pHistory;
    private javax.swing.JPanel pLine;
    private javax.swing.JPanel pLine1;
    private javax.swing.JPanel pMain;
    public javax.swing.JPanel pPinjam;
    private javax.swing.JPanel p_content;
    private javax.swing.JPanel p_nav;
    private javax.swing.JPanel p_side;
    // End of variables declaration//GEN-END:variables

    public void setMainPanel(JPanel panel) {
        pMain.removeAll();
        pMain.add(panel);
        pMain.repaint();
        pMain.revalidate();
    }

}
