/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package npinjamruang;

/**
 *
 * @author dyana
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_nav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_side = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menus = new javax.swing.JPanel();
        bKeluar = new javax.swing.JButton();
        bRuangan = new javax.swing.JButton();
        bRiwayat = new javax.swing.JButton();
        p_content = new javax.swing.JPanel();
        pMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_nav.setBackground(new java.awt.Color(0, 102, 204));
        p_nav.setPreferredSize(new java.awt.Dimension(800, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Pinjam");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("RuangSYS");

        javax.swing.GroupLayout p_navLayout = new javax.swing.GroupLayout(p_nav);
        p_nav.setLayout(p_navLayout);
        p_navLayout.setHorizontalGroup(
            p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_navLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_navLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(699, Short.MAX_VALUE))
        );
        p_navLayout.setVerticalGroup(
            p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_navLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(p_nav, java.awt.BorderLayout.PAGE_START);

        p_side.setPreferredSize(new java.awt.Dimension(200, 525));

        menus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        menus.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 150, 40));

        bRuangan.setText("List Ruangan");
        bRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRuanganActionPerformed(evt);
            }
        });
        menus.add(bRuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 40));

        bRiwayat.setText("Riwayat");
        bRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRiwayatActionPerformed(evt);
            }
        });
        menus.add(bRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 40));

        jScrollPane1.setViewportView(menus);

        javax.swing.GroupLayout p_sideLayout = new javax.swing.GroupLayout(p_side);
        p_side.setLayout(p_sideLayout);
        p_sideLayout.setHorizontalGroup(
            p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_sideLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_sideLayout.setVerticalGroup(
            p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        getContentPane().add(p_side, java.awt.BorderLayout.LINE_START);

        p_content.setBackground(new java.awt.Color(255, 255, 255));

        pMain.setBackground(new java.awt.Color(255, 255, 255));
        pMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout p_contentLayout = new javax.swing.GroupLayout(p_content);
        p_content.setLayout(p_contentLayout);
        p_contentLayout.setHorizontalGroup(
            p_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_contentLayout.setVerticalGroup(
            p_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(p_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(814, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRiwayatActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRuanganActionPerformed
        pMain.removeAll();               // clear panel sebelumnya
        pMain.add(new Ruangan(this));   // tambahkan panel baru
        pMain.revalidate();             // refresh layout
        pMain.repaint();                // gambar ulang

    }//GEN-LAST:event_bRuanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bRiwayat;
    private javax.swing.JButton bRuangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menus;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel p_content;
    private javax.swing.JPanel p_nav;
    private javax.swing.JPanel p_side;
    // End of variables declaration//GEN-END:variables

}
