/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package npinjamruang;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author dyana
 */
public class Ruangan extends javax.swing.JPanel {

   // Di dalam Ruangan.java
private final MainMenu mainMenu;

public Ruangan(MainMenu mainMenu) {
    this.mainMenu = mainMenu;
    initComponents(); 
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/kelas2.jpg"));
        Image img = icon.getImage().getScaledInstance(140, 120, Image.SCALE_SMOOTH);
        lbGambar.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        card = new javax.swing.JPanel();
        bPinjam = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbGambar = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(600, 525));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card.setBackground(new java.awt.Color(204, 204, 204));
        card.setPreferredSize(new java.awt.Dimension(140, 170));
        card.setLayout(new java.awt.BorderLayout());

        bPinjam.setText("Pinjam");
        bPinjam.setPreferredSize(new java.awt.Dimension(75, 30));
        card.add(bPinjam, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 20));

        jLabel2.setText("R201");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        card.add(jPanel2, java.awt.BorderLayout.PAGE_START);
        card.add(lbGambar, java.awt.BorderLayout.CENTER);

        add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 160));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPinjam;
    private javax.swing.JPanel card;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbGambar;
    // End of variables declaration//GEN-END:variables
}
