/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package npinjamruang;

import java.awt.Image;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author dyana
 */
public class Ruangan extends javax.swing.JPanel {

    private MainMenu parent;

    public Ruangan(MainMenu parent) {
        this.parent = parent;
        initComponents();

        lbGambar.setIcon(ImageHelper.getIcon("/img/kelas2.jpg", 140, 120));
        lbGambar1.setIcon(ImageHelper.getIcon("/img/room1.jpg", 140, 120));
        lbGambar2.setIcon(ImageHelper.getIcon("/img/kelas2.jpg", 140, 120));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        card = new javax.swing.JPanel();
        bPinjam1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbGambar = new javax.swing.JLabel();
        card1 = new javax.swing.JPanel();
        bPinjam2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbGambar1 = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        bPinjam3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbGambar2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(600, 525));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        card.setBackground(new java.awt.Color(204, 204, 204));
        card.setPreferredSize(new java.awt.Dimension(140, 170));
        card.setLayout(new java.awt.BorderLayout());

        bPinjam1.setText("Pinjam");
        bPinjam1.setPreferredSize(new java.awt.Dimension(75, 30));
        bPinjam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPinjam1ActionPerformed(evt);
            }
        });
        card.add(bPinjam1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 20));

        jLabel2.setText("R201");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        card.add(jPanel2, java.awt.BorderLayout.PAGE_START);
        card.add(lbGambar, java.awt.BorderLayout.CENTER);

        add(card);

        card1.setBackground(new java.awt.Color(204, 204, 204));
        card1.setPreferredSize(new java.awt.Dimension(140, 170));
        card1.setLayout(new java.awt.BorderLayout());

        bPinjam2.setText("Pinjam");
        bPinjam2.setPreferredSize(new java.awt.Dimension(75, 30));
        bPinjam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPinjam2ActionPerformed(evt);
            }
        });
        card1.add(bPinjam2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(140, 20));

        jLabel3.setText("R201");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        card1.add(jPanel3, java.awt.BorderLayout.PAGE_START);
        card1.add(lbGambar1, java.awt.BorderLayout.CENTER);

        add(card1);

        card2.setBackground(new java.awt.Color(204, 204, 204));
        card2.setPreferredSize(new java.awt.Dimension(140, 170));
        card2.setLayout(new java.awt.BorderLayout());

        bPinjam3.setText("Pinjam");
        bPinjam3.setPreferredSize(new java.awt.Dimension(75, 30));
        bPinjam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPinjam3ActionPerformed(evt);
            }
        });
        card2.add(bPinjam3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(140, 20));

        jLabel4.setText("R201");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        card2.add(jPanel4, java.awt.BorderLayout.PAGE_START);
        card2.add(lbGambar2, java.awt.BorderLayout.CENTER);

        add(card2);
    }// </editor-fold>//GEN-END:initComponents

    private void bPinjam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPinjam1ActionPerformed
        try {
            FormPinjam formPinjam = new FormPinjam();
            formPinjam.setRuangId("R201"); // contoh data, bisa diganti sesuai tombol
            parent.setMainPanel(formPinjam);
        } catch (ParseException ex) {
            Logger.getLogger(Ruangan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bPinjam1ActionPerformed

    private void bPinjam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPinjam2ActionPerformed
        try {
            FormPinjam formPinjam = new FormPinjam();
            formPinjam.setRuangId("R202"); // contoh data, bisa diganti sesuai tombol
            parent.setMainPanel(formPinjam);
        } catch (ParseException ex) {
            Logger.getLogger(Ruangan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bPinjam2ActionPerformed

    private void bPinjam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPinjam3ActionPerformed
        try {
            FormPinjam formPinjam = new FormPinjam();
            formPinjam.setRuangId("R203"); // contoh data, bisa diganti sesuai tombol
            parent.setMainPanel(formPinjam);
        } catch (ParseException ex) {
            Logger.getLogger(Ruangan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bPinjam3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPinjam1;
    private javax.swing.JButton bPinjam2;
    private javax.swing.JButton bPinjam3;
    private javax.swing.JPanel card;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbGambar;
    private javax.swing.JLabel lbGambar1;
    private javax.swing.JLabel lbGambar2;
    // End of variables declaration//GEN-END:variables
}
